In [436]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [437]:
path = 'https://uu-sml.github.io/course-sml-public/data/biopsy.csv'

In [438]:
data=pd.read_csv(path,na_values='?', dtype={'ID': str}).dropna().reset_index()

In [439]:
data.head()

index       ID  V1  V2  V3  V4  V5    V6  V7  V8  V9   class
0      0  1000025   5   1   1   1   2   1.0   3   1   1  benign
1      1  1002945   5   4   4   5   7  10.0   3   2   1  benign
2      2  1015425   3   1   1   1   2   2.0   3   1   1  benign
3      3  1016277   6   8   8   1   3   4.0   3   7   1  benign
4      4  1017023   4   1   1   3   2   1.0   3   1   1  benign

In [441]:
data.shape

(683, 12)

In [442]:
# V1: clump thickness.
# V2: uniformity of cell size.
# V3: uniformity of cell shape.
# V4: marginal adhesion.
# V5: single epithelial cell size.
# V6: bare nuclei (16 values are missing).
# V7: bland chromatin.
# V8: normal nucleoli.
# V9: mitoses.

In [443]:
x=data.iloc[:,2:-1].values
y=data.iloc[:,-1].values

In [444]:
n=data.shape[0]

In [445]:
for i in range(n):
    if y[i]=="benign":y[i]=0
    else:
        y[i]=1

In [446]:
y=y.astype(int)

In [447]:
from sklearn.model_selection import train_test_split

In [448]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

In [449]:
from sklearn.preprocessing import StandardScaler

In [450]:
sc1=StandardScaler()
sc2=StandardScaler()

In [451]:
x_train=sc1.fit_transform(x_train)

In [452]:
x_test=sc2.fit_transform(x_test)

In [453]:
print(x_train)

[[-1.21629973 -0.70863282 -0.75174943 ... -0.99312055 -0.62911518
  -0.36280962]
 [-0.15298932 -0.70863282 -0.41233523 ... -0.58305787 -0.62911518
  -0.36280962]
 [ 0.91032108  0.28358232  1.2847358  ...  1.46725553  1.02611078
  -0.36280962]
 ...
 [ 1.97363148  0.94505909  0.26649318 ... -0.17299519 -0.29806999
   0.8241458 ]
 [-0.86186292 -0.70863282 -0.75174943 ... -0.17299519 -0.62911518
  -0.36280962]
 [ 0.20144748  0.28358232  0.26649318 ...  0.64713017  1.02611078
  -0.36280962]]


In [454]:
print(x_test)

[[ 0.18727336 -0.68459198 -0.71415935 ... -0.61219222 -0.56691757
  -0.31071298]
 [-1.23600418 -0.68459198 -0.71415935 ... -0.20800353 -0.56691757
  -0.31071298]
 [-0.16854602 -0.68459198 -0.71415935 ... -0.20800353 -0.56691757
  -0.31071298]
 ...
 [-0.16854602 -0.68459198 -0.71415935 ... -0.20800353 -0.56691757
  -0.31071298]
 [-0.16854602 -0.68459198 -0.71415935 ... -0.61219222 -0.56691757
  -0.31071298]
 [-0.52436541 -0.68459198 -0.71415935 ... -0.61219222 -0.56691757
  -0.31071298]]


In [455]:
print(y_train)
print(y_test)

[0 0 1 0 1 1 0 1 0 1 0 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0
 1 1 1 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 0 1 1 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0
 1 1 1 1 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 1 0 0 1 0 0 0
 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0
 1 0 1 1 1 1 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 1 1
 1 1 1 0 0 1 1 0 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0
 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 1 0 1
 0 1 0 0 1 1 0 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 1 1 1
 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0
 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1
 0 1 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 0 1 1 1
 0 0 1 1 0 0 0 0 1 0 1 0 

In [456]:
from sklearn.svm import SVC

In [457]:
classifier=SVC(kernel='rbf',random_state=1)

In [458]:
classifier.fit(x_train,y_train)

SVC(random_state=1)

In [459]:
y_pred=classifier.predict(x_test)

In [460]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [461]:
cm=confusion_matrix(y_pred,y_test)

In [462]:
print(cm)

[[111   1]
 [  0  59]]


In [463]:
accuracy_score(y_pred,y_test)

0.9941520467836257

In [464]:
print(y_pred)

[0 0 0 1 0 1 0 0 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 1 0
 0 1 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 1 1 0 0 1 0 0
 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1 0 0 1 1 0 0 1 0 0 1 1 0 0 0 0 1 0 1
 1 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 0 0 0 1
 0 0 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 1 0 1 0 0 0]


In [465]:
y_pred_1=classifier.predict(x_train)

In [466]:
print(y_pred_1)

[0 0 1 0 1 1 1 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1 1 0 0 0 1 0 0 1 0 1 0 1 0 1 0
 1 1 1 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 0 1 0 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 0 1 1 0 1 1 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 1 0
 1 1 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0
 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0
 1 0 0 1 1 1 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 0 0 1
 1 1 1 0 0 1 1 0 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0
 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 1 0 0 0 1 0 0 1 1 0 1
 0 1 0 0 1 1 0 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 1 1 1
 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0
 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 1 0 1
 0 1 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 0 1 1 1
 0 0 1 1 0 0 0 0 1 0 1 0 

In [467]:
classifier.predict(sc2.transform([[5.0,1.0,1.0,1.0,2.0,1.0,3.0,1.0,1.0]]))

array([0])

In [468]:
classifier.predict(sc2.transform([[3.0,1.0,1.0,1.0,2.0,2.0,3.0,1.0,1.0]]))

array([0])

In [469]:
print(sc2.transform([[3.0,1.0,1.0,1.0,2.0,2.0,3.0,1.0,1.0]]))

[[-0.52436541 -0.68459198 -0.71415935 -0.59011552 -0.55505327 -0.3885894
  -0.20800353 -0.56691757 -0.31071298]]


In [470]:
print(classifier.predict(sc2.transform([[5,5,5,5,5,5,5,5,5]])))

[1]
